# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

matrix:
  include:
   - r: release
     after_success:
       - Rscript -e 'covr::codecov(function_exclusions = c("\\.onLoad$", "^mb_tl_complete$"), line_exclusions = list("R/novels.R" = 20:21, "R/api.R" = 82, "R/memory_alpha.R" = c(171, 200, 227), "R/memory_beta.R" = c(112, 141, 168), "R/fonts.R" = c(22:23, 26:27, 30:31)))'
   - r: devel
     r_build_args: --no-build-vignettes
     r_check_args: --ignore-vignettes --no-examples
   - r: oldrel
     r_build_args: --no-build-vignettes
     r_check_args: --ignore-vignettes --no-examples
   - os: osx
     r: release
     before_install: ''
     disable_homebrew: false
